import styles from '../../styles/modules/Home.module.css'
import TheHeader from '../structure/TheHeader'
import TheFooter from '../structure/TheFooter'
import Head from 'next/head'

export default function DefaultLayout({ children }: {children: JSX.Element | JSX.Element[]}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TheHeader/>
      <main className={styles.main}>
        {children}
      </main>
      <TheFooter/>
    </>
  )
}